--local DEBUGGER_PATH = vim.fn.stdpath "data" .. "/site/pack/packer/opt/vscode-js-debug"
--local dap = require('dap')

--  require("dap-vscode-js").setup {
--    node_path = "node",
--    debugger_path = DEBUGGER_PATH,
--    -- debugger_cmd = { "js-debug-adapter" },
--    adapters = { "pwa-node", "pwa-chrome", "pwa-msedge", "node-terminal", "pwa-extensionHost" }, -- which adapters to register in nvim-dap
--  }

--  local exts = {
--  'javascript',
--  'typescript',
--  'javascriptreact',
--  'typescriptreact',
--}

--for i, ext in ipairs(exts) do
--  dap.configurations[ext] = {
--      {
--          type = 'pwa-node',
--          request = 'launch',
--          name = 'Launch Current File (pwa-node)',
--          cwd = vim.fn.getcwd(),
--          args = { '${file}' },
--          sourceMaps = true,
--          protocol = 'inspector',
--      },
--     {
--      type = 'pwa-node',
--      request = 'launch',
--      name = 'Launch Current File (pwa-node with ts-node)',
--      cwd = vim.fn.getcwd(),
--      --runtimeArgs = {},
--    runtimeExecutable = 'ts-node',
--      args = { '${file}' },
--      sourceMaps = true,
--      protocol = 'inspector',
--      skipFiles = { '<node_internals>/**', 'node_modules/**' },
--      resolveSourceMapLocations = {
--        "${workspaceFolder}/**",
--        "!**/node_modules/**",
--      },
--    },
--    {
--      type = 'pwa-node',
--      request = 'launch',
--      name = 'Launch Test Current File (pwa-node with jest)',
--      cwd = vim.fn.getcwd(),
--      runtimeArgs = { '${workspaceFolder}/node_modules/.bin/jest' },
--      runtimeExecutable = 'node',
--      args = { '${file}', '--coverage', 'false'},
--      rootPath = '${workspaceFolder}',
--      sourceMaps = true,
--      console = 'integratedTerminal',
--      internalConsoleOptions = 'neverOpen',
--      skipFiles = { '<node_internals>/**', 'node_modules/**' },
--    },
--  }
--end
